
export const CATEGORY_CHOICES = [
    ('Industry', 'Category: Industry'),
    ('Video production', 'Category: Marketing, PR and Design > Video production'),
    ('Graphic design', 'Category: Marketing, PR and Design > Graphic design'),
    ('Web Design', 'Category: Marketing, PR and Design > Web Design'),
    ('Photography', 'Category: Marketing, PR and Design > Photography'),
    ('Advertising agency', 'Category: Marketing, PR and Design > Advertising agency'),
    ('SEO Marketing', 'Category: Marketing, PR and Design > SEO Marketing'),
    ('SEA Marketing', 'Category: Marketing, PR and Design > SEA Marketing'),
    ('Social Media Marketing', 'Category: Marketing, PR and Design > Social Media Marketing'),
    ('Journalism and editing', 'Category: Marketing, PR and Design > Journalism and editing'),
    ('Others', 'Category: Marketing, PR and Design > Others'),
    ('Photography', 'Category: Art and entertainment > Photography'),
    ('Musician', 'Category: Art and entertainment > Musician'),
    ('DJ', 'Category: Art and entertainment > DJ'),
    ('Artists', 'Category: Art and entertainment > Artists'),
    ('Event production', 'Category: Art and entertainment > Event production'),
    ('Others', 'Category: Art and entertainment > Others'),
    ('External sales', 'Category: Consumer goods and distribution > External sales'),
    ('Retail trade', 'Category: Consumer goods and distribution > Retail trade'),
    ('Retailers', 'Category: Consumer goods and distribution > Retailers'),
    ('Ecommerce or online store', 'Category: Consumer goods and distribution > Ecommerce or online store'),
    ('Sales partner', 'Category: Consumer goods and distribution > Sales partner'),
    ('Manufacturer or producer', 'Category: Consumer goods and distribution > Manufacturer or producer'),
    ('Others', 'Category: Consumer goods and distribution > Others'),
    ('Software development', 'Category: IT, EDP and telecommunications > Software development'),
    ('IT consulting', 'Category: IT, EDP and telecommunications > IT consulting'),
    ('IT security', 'Category: IT, EDP and telecommunications > IT security'),
    ('Smartphone Services', 'Category: IT, EDP and telecommunications > Smartphone Services'),
    ('Cloud services', 'Category: IT, EDP and telecommunications > Cloud services'),
    ('Hosting and Providing', 'Category: IT, EDP and telecommunications > Hosting and Providing'),
    ('Computer technology', 'Category: IT, EDP and telecommunications > Computer technology'),
    ('Telecommunications', 'Category: IT, EDP and telecommunications > Telecommunications'),
    ('Machine Learning', 'Category: IT, EDP and telecommunications > Machine Learning'),
    ('Others', 'Category: IT, EDP and telecommunications > Others'),
    ('Fitness', 'Category: Sport and health > Fitness'),
    ('Nursing', 'Category: Sport and health > Nursing'),
    ('Medicine or pharmacy', 'Category: Sport and health > Medicine or pharmacy'),
    ('Medical practice for general medicine', 'Category: Sport and health > Medical practice for general medicine'),
    ('Nutrition', 'Category: Sport and health > Nutrition'),
    ('Rehabilitation', 'Category: Sport and health > Rehabilitation'),
    ('Medicine', 'Category: Sport and health > Medicine'),
    ('Coaching and seminars', 'Category: Sport and health > Coaching and seminars'),
    ('Dental practice', 'Category: Sport and health > Dental practice'),
    ('Specialist practice', 'Category: Sport and health > Specialist practice'),
    ('Massage practice', 'Category: Sport and health > Massage practice'),
    ('Physiotherapy', 'Category: Sport and health > Physiotherapy'),
    ('Nursing home', 'Category: Sport and health > Nursing home'),
    ('Clubs', 'Category: Sport and health > Clubs'),
    ('Others', 'Category: Sport and health > Others'),
    ('Training', 'Category: Education, education and science > Training'),
    ('Further education', 'Category: Education, education and science > Further education'),
    ('Organizations', 'Category: Education, education and science > Organizations'),
    ('Coaching and seminars', 'Category: Education, education and science > Coaching and seminars'),
    ('Clubs', 'Category: Education, education and science > Clubs'),
    ('Others', 'Category: Education, education and science > Others'),
    ('Water technology', 'Category: Energy supply and environment > Water technology'),
    ('Solar technology and photovoltaics', 'Category: Energy supply and environment > Solar technology and photovoltaics'),
    ('Recycling', 'Category: Energy supply and environment > Recycling'),
    ('Air Conditioning', 'Category: Energy supply and environment > Air Conditioning'),
    ('Heating Technology', 'Category: Energy supply and environment > Heating Technology'),
    ('Refrigeration technology', 'Category: Energy supply and environment > Refrigeration technology'),
    ('Agriculture', 'Category: Energy supply and environment > Agriculture'),
    ('Others', 'Category: Energy supply and environment > Others'),
    ('Motor vehicle', 'Category: Industry and mechanical engineering > Motor vehicle'),
    ('Logistics or transport', 'Category: Industry and mechanical engineering > Logistics or transport'),
    ('Steel or metal technology', 'Category: Industry and mechanical engineering > Steel or metal technology'),
    ('Hydraulic', 'Category: Industry and mechanical engineering > Hydraulic'),
    ('Others', 'Category: Industry and mechanical engineering > Others'),
    ('Tour operators', 'Category: Tourism > Tour operators'),
    ('Hotel or accommodation', 'Category: Tourism > Hotel or accommodation'),
    ('Car rental', 'Category: Tourism > Car rental'),
    ('Adventures', 'Category: Tourism > Adventures'),
    ('Others', 'Category: Tourism > Others'),
    ('Legal advice', 'Category: Audit, Taxes and Law > Legal advice'),
    ('Auditing', 'Category: Audit, Taxes and Law > Auditing'),
    ('Tax consultant', 'Category: Audit, Taxes and Law > Tax consultant'),
    ('Others', 'Category: Audit, Taxes and Law > Others'),
    ('Catering', 'Category: Gastronomy > Catering'),
    ('Restaurant', 'Category: Gastronomy > Restaurant'),
    ('Inn', 'Category: Gastronomy > Inn'),
    ('Delivery service', 'Category: Gastronomy > Delivery service'),
    ('Coffee shop', 'Category: Gastronomy > Coffee shop'),
    ('Bar', 'Category: Gastronomy > Bar'),
    ('Bakery', 'Category: Gastronomy > Bakery'),
    ('Cake shop', 'Category: Gastronomy > Cake shop'),
    ('Others', 'Category: Gastronomy > Others'),
    ('Personal Service', 'Category: Consulting > Personal Service'),
    ('Advertising agency', 'Category: Consulting > Advertising agency'),
    ('Consulting', 'Category: Consulting > Consulting'),
    ('Coaching and seminars', 'Category: Consulting > Coaching and seminars'),
    ('Legal advice', 'Category: Consulting > Legal advice'),
    ('Personal protection / security service', 'Category: Consulting > Personal protection / security service'),
    ('Others', 'Category: Consulting > Others'),
    ('Furnishing', 'Category: Housing and construction > Furnishing'),
    ('Cleaning service', 'Category: Housing and construction > Cleaning service'),
    ('Construction planning and architecture', 'Category: Housing and construction > Construction planning and architecture'),
    ('Real estate sales', 'Category: Housing and construction > Real estate sales'),
    ('Immobilienvermietung', 'Category: Housing and construction > Immobilienvermietung'),
    ('House technic', 'Category: Housing and construction > House technic'),
    ('Building service', 'Category: Housing and construction > Building service'),
    ('Heating Technology', 'Category: Housing and construction > Heating Technology'),
    ('Smart home technology', 'Category: Housing and construction > Smart home technology'),
    ('Others', 'Category: Housing and construction > Others'),
    ('Printing house', 'Category: Publishing and printed matter > Printing house'),
    ('Newsprint', 'Category: Publishing and printed matter > Newsprint'),
    ('Printing and media prepress', 'Category: Publishing and printed matter > Printing and media prepress'),
    ('Books publishing', 'Category: Publishing and printed matter > Books publishing'),
    ('Newspaper publisher', 'Category: Publishing and printed matter > Newspaper publisher'),
    ('Others', 'Category: Publishing and printed matter > Others'),
    ('Electrical engineering', 'Category: Craft and construction industry > Electrical engineering'),
    ('Car repair', 'Category: Craft and construction industry > Car repair'),
    ('Floristry', 'Category: Craft and construction industry > Floristry'),
    ('Landscaping', 'Category: Craft and construction industry > Landscaping'),
    ('Hair stylist', 'Category: Craft and construction industry > Hair stylist'),
    ('Plumbing', 'Category: Craft and construction industry > Plumbing'),
    ('Carpenter', 'Category: Craft and construction industry > Carpenter'),
    ('Carpenter', 'Category: Craft and construction industry > Carpenter'),
    ('Glazier and window maker', 'Category: Craft and construction industry > Glazier and window maker'),
    ('Floor design', 'Category: Craft and construction industry > Floor design'),
    ('Engineering', 'Category: Craft and construction industry > Engineering'),
    ('Assembly', 'Category: Craft and construction industry > Assembly'),
    ('Construction planning and architecture', 'Category: Craft and construction industry > Construction planning and architecture'),
    ('Heating Technology', 'Category: Craft and construction industry > Heating Technology'),
    ('Refrigeration technology', 'Category: Craft and construction industry > Refrigeration technology'),
    ('Painter', 'Category: Craft and construction industry > Painter'),
    ('Others', 'Category: Craft and construction industry > Others'),
]


