export const COUNTRIES_CHOICES = [
    { value: 'AFG', label: 'Afghanistan' },
    { value: 'ALB', label: 'Albania' },
    { value: 'DZA', label: 'Algeria' },
    { value: 'AND', label: 'Andorra' },
    { value: 'AGO', label: 'Angola' },
    { value: 'ATG', label: 'Antigua and Barbuda' },
    { value: 'ARG', label: 'Argentina' },
    { value: 'ARM', label: 'Armenia' },
    { value: 'AUS', label: 'Australia' },
    { value: 'AUT', label: 'Austria' },
    { value: 'AZE', label: 'Azerbaijan' },
    { value: 'BHS', label: 'Bahamas' },
    { value: 'BHR', label: 'Bahrain' },
    { value: 'BGD', label: 'Bangladesh' },
    { value: 'BRB', label: 'Barbados' },
    { value: 'BLR', label: 'Belarus' },
    { value: 'BEL', label: 'Belgium' },
    { value: 'BLZ', label: 'Belize' },
    { value: 'BEN', label: 'Benin' },
    { value: 'BTN', label: 'Bhutan' },
    { value: 'BOL', label: 'Bolivia (Plurinational State of)' },
    { value: 'BIH', label: 'Bosnia and Herzegovina' },
    { value: 'BWA', label: 'Botswana' },
    { value: 'BRA', label: 'Brazil' },
    { value: 'BRN', label: 'Brunei Darussalam' },
    { value: 'BGR', label: 'Bulgaria' },
    { value: 'BFA', label: 'Burkina Faso' },
    { value: 'BDI', label: 'Burundi' },
    { value: 'CPV', label: 'Cabo Verde' },
    { value: 'KHM', label: 'Cambodia' },
    { value: 'CMR', label: 'Cameroon' },
    { value: 'CAN', label: 'Canada' },
    { value: 'CAF', label: 'Central African Republic' },
    { value: 'TCD', label: 'Chad' },
    { value: 'CHL', label: 'Chile' },
    { value: 'CHN', label: 'China' },
    { value: 'COL', label: 'Colombia' },
    { value: 'COM', label: 'Comoros' },
    { value: 'COG', label: 'Congo' },
    { value: 'CRI', label: 'Costa Rica' },
    { value: 'HRV', label: 'Croatia' },
    { value: 'CUB', label: 'Cuba' },
    { value: 'CYP', label: 'Cyprus' },
    { value: 'CZE', label: 'Czechia' },
    { value: 'COD', label: 'Democratic Republic of the Congo' },
    { value: 'DNK', label: 'Denmark' },
    { value: 'DJI', label: 'Djibouti' },
    { value: 'DMA', label: 'Dominica' },
    { value: 'DOM', label: 'Dominican Republic' },
    { value: 'ECU', label: 'Ecuador' },
    { value: 'EGY', label: 'Egypt' },
    { value: 'SLV', label: 'El Salvador' },
    { value: 'GNQ', label: 'Equatorial Guinea' },
    { value: 'ERI', label: 'Eritrea' },
    { value: 'EST', label: 'Estonia' },
    { value: 'SWZ', label: 'Eswatini' },
    { value: 'ETH', label: 'Ethiopia' },
    { value: 'FJI', label: 'Fiji' },
    { value: 'FIN', label: 'Finland' },
    { value: 'FRA', label: 'France' },
    { value: 'GAB', label: 'Gabon' },
    { value: 'GMB', label: 'Gambia' },
    { value: 'GEO', label: 'Georgia' },
    { value: 'DEU', label: 'Germany' },
    { value: 'GHA', label: 'Ghana' },
    { value: 'GRC', label: 'Greece' },
    { value: 'GRD', label: 'Grenada' },
    { value: 'GTM', label: 'Guatemala' },
    { value: 'GIN', label: 'Guinea' },
    { value: 'GNB', label: 'Guinea-Bissau' },
    { value: 'GUY', label: 'Guyana' },
    { value: 'HTI', label: 'Haiti' },
    { value: 'HND', label: 'Honduras' },
    { value: 'HUN', label: 'Hungary' },
    { value: 'ISL', label: 'Iceland' },
    { value: 'IND', label: 'India' },
    { value: 'IDN', label: 'Indonesia' },
    { value: 'IRN', label: 'Iran (Islamic Republic of)' },
    { value: 'IRQ', label: 'Iraq' },
    { value: 'IRL', label: 'Ireland' },
    { value: 'ISR', label: 'Israel' },
    { value: 'ITA', label: 'Italy' },
    { value: 'JAM', label: 'Jamaica' },
    { value: 'JPN', label: 'Japan' },
    { value: 'JOR', label: 'Jordan' },
    { value: 'KAZ', label: 'Kazakhstan' },
    { value: 'KEN', label: 'Kenya' },
    { value: 'KIR', label: 'Kiribati' },
    { value: 'KWT', label: 'Kuwait' },
    { value: 'KGZ', label: 'Kyrgyzstan' },
    { value: 'LAO', label: "Lao People's Democratic Republic" },
    { value: 'LVA', label: 'Latvia' },
    { value: 'LBN', label: 'Lebanon' },
    { value: 'LSO', label: 'Lesotho' },
    { value: 'LBR', label: 'Liberia' },
    { value: 'LBY', label: 'Libya' },
    { value: 'LIE', label: 'Liechtenstein' },
    { value: 'LTU', label: 'Lithuania' },
    { value: 'LUX', label: 'Luxembourg' },
    { value: 'MDG', label: 'Madagascar' },
    { value: 'MWI', label: 'Malawi' },
    { value: 'MYS', label: 'Malaysia' },
    { value: 'MDV', label: 'Maldives' },
    { value: 'MLI', label: 'Mali' },
    { value: 'MLT', label: 'Malta' },
    { value: 'MHL', label: 'Marshall Islands' },
    { value: 'MRT', label: 'Mauritania' },
    { value: 'MUS', label: 'Mauritius' },
    { value: 'MEX', label: 'Mexico' },
    { value: 'FSM', label: 'Micronesia (Federated States of)' },
    { value: 'MCO', label: 'Monaco' },
    { value: 'MNG', label: 'Mongolia' },
    { value: 'MNE', label: 'Montenegro' },
    { value: 'MAR', label: 'Morocco' },
    { value: 'MOZ', label: 'Mozambique' },
    { value: 'MMR', label: 'Myanmar' },
    { value: 'NAM', label: 'Namibia' },
    { value: 'NRU', label: 'Nauru' },
    { value: 'NPL', label: 'Nepal' },
    { value: 'NLD', label: 'Netherlands' },
    { value: 'NZL', label: 'New Zealand' },
    { value: 'NIC', label: 'Nicaragua' },
    { value: 'NER', label: 'Niger' },
    { value: 'NGA', label: 'Nigeria' },
    { value: 'PRK', label: "Democratic People's Republic of Korea" },
    { value: 'MKD', label: 'North Macedonia' },
    { value: 'NOR', label: 'Norway' },
    { value: 'OMN', label: 'Oman' },
    { value: 'PAK', label: 'Pakistan' },
    { value: 'PLW', label: 'Palau' },
    { value: 'PAN', label: 'Panama' },
    { value: 'PNG', label: 'Papua New Guinea' },
    { value: 'PRY', label: 'Paraguay' },
    { value: 'PER', label: 'Peru' },
    { value: 'PHL', label: 'Philippines' },
    { value: 'POL', label: 'Poland' },
    { value: 'PRT', label: 'Portugal' },
    { value: 'QAT', label: 'Qatar' },
    { value: 'KOR', label: 'Republic of Korea' },
    { value: 'MDA', label: 'Republic of Moldova' },
    { value: 'ROU', label: 'Romania' },
    { value: 'RUS', label: 'Russian Federation' },
    { value: 'RWA', label: 'Rwanda' },
    { value: 'KNA', label: 'Saint Kitts and Nevis' },
    { value: 'LCA', label: 'Saint Lucia' },
    { value: 'VCT', label: 'Saint Vincent and the Grenadines' },
    { value: 'WSM', label: 'Samoa' },
    { value: 'SMR', label: 'San Marino' },
    { value: 'STP', label: 'Sao Tome and Principe' },
    { value: 'SAU', label: 'Saudi Arabia' },
    { value: 'SEN', label: 'Senegal' },
    { value: 'SRB', label: 'Serbia' },
    { value: 'SYC', label: 'Seychelles' },
    { value: 'SLE', label: 'Sierra Leone' },
    { value: 'SGP', label: 'Singapore' },
    { value: 'SVK', label: 'Slovakia' },
    { value: 'SVN', label: 'Slovenia' },
    { value: 'SLB', label: 'Solomon Islands' },
    { value: 'SOM', label: 'Somalia' },
    { value: 'ZAF', label: 'South Africa' },
    { value: 'SSD', label: 'South Sudan' },
    { value: 'ESP', label: 'Spain' },
    { value: 'LKA', label: 'Sri Lanka' },
    { value: 'SDN', label: 'Sudan' },
    { value: 'SUR', label: 'Suriname' },
    { value: 'SWE', label: 'Sweden' },
    { value: 'CHE', label: 'Switzerland' },
    { value: 'SYR', label: 'Syrian Arab Republic' },
    { value: 'TJK', label: 'Tajikistan' },
    { value: 'THA', label: 'Thailand' },
    { value: 'TLS', label: 'Timor-Leste' },
    { value: 'TGO', label: 'Togo' },
    { value: 'TON', label: 'Tonga' },
    { value: 'TTO', label: 'Trinidad and Tobago' },
    { value: 'TUN', label: 'Tunisia' },
    { value: 'TUR', label: 'Turkey' },
    { value: 'TKM', label: 'Turkmenistan' },
    { value: 'TUV', label: 'Tuvalu' },
    { value: 'UGA', label: 'Uganda' },
    { value: 'UKR', label: 'Ukraine' },
    { value: 'ARE', label: 'United Arab Emirates' },
    { value: 'GBR', label: 'United Kingdom of Great Britain and Northern Ireland' },
    { value: 'TZA', label: 'United Republic of Tanzania' },
    { value: 'USA', label: 'United States of America' },
    { value: 'URY', label: 'Uruguay' },
    { value: 'UZB', label: 'Uzbekistan' },
    { value: 'VUT', label: 'Vanuatu' },
    { value: 'VEN', label: 'Venezuela (Bolivarian Republic of)' },
    { value: 'VNM', label: 'Viet Nam' },
    { value: 'YEM', label: 'Yemen' },
    { value: 'ZMB', label: 'Zambia' },
    { value: 'ZWE', label: 'Zimbabwe' },
  ];
  
  export const LANGUAGES_CHOICES = [
    { value: 'en', label: 'English' },
    { value: 'es', label: 'Spanish' },
    { value: 'fr', label: 'French' },
    { value: 'de', label: 'German' },
    { value: 'zh', label: 'Chinese' },
    { value: 'ru', label: 'Russian' },
    { value: 'ar', label: 'Arabic' },
    { value: 'ja', label: 'Japanese' },
    { value: 'pt', label: 'Portuguese' },
    { value: 'bn', label: 'Bengali' },
    { value: 'pa', label: 'Punjabi' },
    { value: 'ko', label: 'Korean' },
    { value: 'vi', label: 'Vietnamese' },
    { value: 'it', label: 'Italian' },
    { value: 'th', label: 'Thai' },
    { value: 'tr', label: 'Turkish' },
    { value: 'el', label: 'Greek' },
    { value: 'nl', label: 'Dutch' },
    { value: 'pl', label: 'Polish' },
    { value: 'uk', label: 'Ukrainian' },
    { value: 'ro', label: 'Romanian' },
    { value: 'hu', label: 'Hungarian' },
    { value: 'cs', label: 'Czech' },
    { value: 'sv', label: 'Swedish' },
    { value: 'fi', label: 'Finnish' },
    { value: 'da', label: 'Danish' },
    { value: 'no', label: 'Norwegian' },
    { value: 'he', label: 'Hebrew' },
    { value: 'id', label: 'Indonesian' },
    { value: 'ms', label: 'Malay' },
    { value: 'tl', label: 'Tagalog' },
    { value: 'sw', label: 'Swahili' },
    { value: 'hi', label: 'Hindi' },
    { value: 'gu', label: 'Gujarati' },
    { value: 'ta', label: 'Tamil' },
    { value: 'te', label: 'Telugu' },
    { value: 'ml', label: 'Malayalam' },
    { value: 'kn', label: 'Kannada' },
    { value: 'mr', label: 'Marathi' },
    { value: 'ur', label: 'Urdu' },
    { value: 'fa', label: 'Persian' },
    { value: 'bh', label: 'Bihari' },
    { value: 'ne', label: 'Nepali' },
    { value: 'si', label: 'Sinhalese' },
    { value: 'lv', label: 'Latvian' },
    { value: 'lt', label: 'Lithuanian' },
    { value: 'et', label: 'Estonian' },
    { value: 'ka', label: 'Georgian' },
    { value: 'hy', label: 'Armenian' },
    { value: 'az', label: 'Azerbaijani' },
    { value: 'kk', label: 'Kazakh' },
    { value: 'uz', label: 'Uzbek' },
    { value: 'tk', label: 'Turkmen' },
    { value: 'ky', label: 'Kyrgyz' },
    { value: 'tg', label: 'Tajik' },
    { value: 'ps', label: 'Pashto' },
    { value: 'sd', label: 'Sindhi' },
    { value: 'dv', label: 'Dhivehi' },
    { value: 'ug', label: 'Uighur' },
    { value: 'bo', label: 'Tibetan' },
    { value: 'dz', label: 'Dzongkha' },
    { value: 'my', label: 'Burmese' },
    { value: 'km', label: 'Khmer' },
    { value: 'lo', label: 'Lao' },
    { value: 'mg', label: 'Malagasy' },
    { value: 'sn', label: 'Shona' },
    { value: 'am', label: 'Amharic' },
    { value: 'ti', label: 'Tigrinya' },
    { value: 'om', label: 'Oromo' },
    { value: 'so', label: 'Somali' },
    { value: 'ig', label: 'Igbo' },
    { value: 'yo', label: 'Yoruba' },
    { value: 'ha', label: 'Hausa' },
    { value: 'zu', label: 'Zulu' },
    { value: 'xh', label: 'Xhosa' },
    { value: 'st', label: 'Southern Sotho' },
    { value: 'tn', label: 'Tswana' },
    { value: 'ts', label: 'Tsonga' },
    { value: 'ss', label: 'Swati' },
    { value: 'nr', label: 'Northern Ndebele' },
    { value: 'nd', label: 'Southern Ndebele' },
    { value: 'chy', label: 'Cheyenne' },
    { value: 'arw', label: 'Arawakan' },
    { value: 'paa', label: 'Papuan' },
    { value: 'afr', label: 'Afrikaans' },
    { value: 'amh', label: 'Amharic' },
    { value: 'arc', label: 'Aramaic' },
    { value: 'bas', label: 'Basa' },
    { value: 'bem', label: 'Bemba' },
    { value: 'bej', label: 'Beja' },
    { value: 'bis', label: 'Bislama' },
    { value: 'bua', label: 'Buriat' },
    { value: 'car', label: 'Carib' },
    { value: 'ceb', label: 'Cebuano' },
    { value: 'chk', label: 'Chuukese' },
    { value: 'cor', label: 'Cornish' },
    { value: 'cos', label: 'Corsican' },
    { value: 'div', label: 'Divehi' },
    { value: 'fij', label: 'Fijian' },
    { value: 'fur', label: 'Friulian' },
    { value: 'frr', label: 'Frisian' },
    { value: 'gaa', label: 'Ga' },
    { value: 'glg', label: 'Galician' },
    { value: 'got', label: 'Gothic' },
    { value: 'haw', label: 'Hawaiian' },
    { value: 'iku', label: 'Inuktitut' },
    { value: 'ilo', label: 'Iloko' },
    { value: 'inh', label: 'Ingush' },
    { value: 'kal', label: 'Kalaallisut' },
    { value: 'kik', label: 'Kikuyu' },
    { value: 'kin', label: 'Kinyarwanda' },
    { value: 'kir', label: 'Kirghiz' },
    { value: 'kon', label: 'Kongo' },
    { value: 'lug', label: 'Luganda' },
    { value: 'lua', label: 'Luba-Kasai' },
    { value: 'luo', label: 'Luo (Kenya and Tanzania)' },
    { value: 'luy', label: 'Luyia' },
    { value: 'mdf', label: 'Moksha' },
    { value: 'mhr', label: 'Mari (Russia)' },
    { value: 'mfe', label: 'Morisyen' },
    { value: 'min', label: 'Minangkabau' },
    { value: 'moh', label: 'Mohawk' },
    { value: 'nan', label: 'Min Nan Chinese' },
    { value: 'nap', label: 'Neapolitan' },
    { value: 'ndo', label: 'Ndonga' },
    { value: 'nso', label: 'Northern Sotho' },
    { value: 'nyo', label: 'Nyoro' },
    { value: 'oci', label: 'Occitan' },
    { value: 'olo', label: 'Livvi-Karelian' },
    { value: 'orm', label: 'Oromo' },
    { value: 'pag', label: 'Pangasinan' },
    { value: 'pam', label: 'Kapampangan' },
    { value: 'pap', label: 'Papiamento' },
    { value: 'pcd', label: 'Picard' },
    { value: 'pdc', label: 'Pennsylvania German' },
    { value: 'pnb', label: 'Western Punjabi' },
    { value: 'ppl', label: 'Pipil' },
    { value: 'quc', label: 'K iche' },
    { value: 'roh', label: 'Romansh' },
    { value: 'rue', label: 'Rusyn' },
    { value: 'sah', label: 'Yakut' },
    { value: 'scn', label: 'Sicilian' },
    { value: 'sco', label: 'Scots' },
    { value: 'sma', label: 'Southern Sami' },
    { value: 'smj', label: 'Lule Sami' },
    { value: 'smn', label: 'Inari Sami' },
    { value: 'sms', label: 'Skolt Sami' },
    { value: 'son', label: 'Songhai' },
    { value: 'sot', label: 'Sotho' },
    { value: 'suk', label: 'Sukuma' },
    { value: 'sus', label: 'Susu' },
    { value: 'syc', label: 'Classical Syriac' },
    { value: 'syr', label: 'Syriac' },
    { value: 'tet', label: 'Tetum' },
    { value: 'tig', label: 'Tigre' },
    { value: 'tiv', label: 'Tiv' },
    { value: 'tkl', label: 'Tokelauan' },
    { value: 'tli', label: 'Tlingit' },
    { value: 'tpi', label: 'Tok Pisin' },
    { value: 'tum', label: 'Tumbuka' },
    { value: 'tvl', label: 'Tuvaluan' },
    { value: 'tyv', label: 'Tuvinian' },
    { value: 'udm', label: 'Udmurt' },
    { value: 'vep', label: 'Veps' },
    { value: 'vls', label: 'West Flemish' },
    { value: 'war', label: 'Waray' },
    { value: 'wln', label: 'Walloon' },
    { value: 'xal', label: 'Kalmyk' },
    { value: 'yid', label: 'Yiddish' },
    { value: 'zap', label: 'Zapotec' },
  ];
  